### ISSUE TITLE
[Suggestion] Broach common (enterprise) frameworks (Spring/Hibernate) and tools (Atlassian stack/certain Git-Clients ;) )

### ISSUE THREAD

**Issue by drandarov-io** [stevenschwenke/SoftwareEngineeringCourse#1]
Most students have no idea and will never hear about frameworks and tools like Spring/Hibernate/the Atlassian stack/certain Git-Clients (that have free Pro-Versions for students)/certain IDEs/etc. in their entire studies, so at least broaching that subject is quite important. 

If you have at least heard of these tools and frameworks or even the concepts, that will help tremendously with finding a job after university.

**Comment by stevenschwenke** [comment]
Thanks for your suggestion - absolutely agree! Already planned: Short comparison between JEE and Spring, including concepts and patterns. Then some more in-depth topics in Spring. Maybe there will be an exercisse with a little Spring application, don't know yet. :)
