### ISSUE TITLE
Hello X-Arguments cut off on folio 2 of Ch. 4 "Maven"

### ISSUE THREAD

**Issue by ChargingBulle** [stevenschwenke/SoftwareEngineeringCourse#32]
![](https://i.imgur.com/EtgrB5r.png)
<sub>Folio 2, [Maven_slides.pptx](https://github.com/stevenschwenke/SoftwareEngineeringCourse/blob/develop/04_Maven/Maven_slides.pptx)</sub>

"Hello Universe" and "Hello Everyone" not comprehensible from context. Argument 2 and 3 cut off.

	C:\>javac greetings\Hello.java
	C:\>dir greetings /B
	Hello.class
	Hello.java
	C:\>java greetings.Hello World Universe Everyone
	Hello World
	Hello Universe  
	Hello Everyone

<sub>Proper Code, Line 25ff [Maven_script.adoc](https://github.com/stevenschwenke/SoftwareEngineeringCourse/blob/develop/04_Maven/Maven_script.adoc)</sub>

**Comment by stevenschwenke** [comment]
Thanks - didn't notice that.
